### ISSUE TITLE
Error message on build of Alpine/Docker

### ISSUE THREAD

**Issue by shawnvoseRP** [realpage/php#18] opened 2016-10-24 17:42 UTC
When I run the build.sh with no modifcations to any images I see the below. I have made sure my docker tool box is up to date. If I go directly to the directory where the alpine Docker file exists and docker build . I get the same error.

 .phpize-deps-0:
    masked in: cache
    satisfies: world[.phpize-deps]
The command '/bin/sh -c apk add --update --no-cache "postgresql-dev@edge>9.5" "libpq@edge>9.5"     && docker-php-ext-install mcrypt mbstring pgsql pdo pdo_pgsql' returned a non-zero code: 56

**Comment by mh3720** [comment] 2016-10-24 23:00
I get the same error.  Here is the relevant portion of the build output:

```
Executing busybox-1.24.2-r9.trigger
OK: 33 MiB in 37 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  musl-1.1.14-r11:
    breaks: musl-dev-1.1.14-r13[musl=1.1.14-r13]
    satisfies: .php-rundeps-0[musl]
               musl-utils-1.1.14-r11[musl=1.1.14-r11]
               musl-utils-1.1.14-r11[so:libc.musl-x86_64.so.1]
               pkgconf-0.9.12-r0[so:libc.musl-x86_64.so.1]
               gcc-5.3.0-r0[so:libc.musl-x86_64.so.1]
               binutils-libs-2.26-r0[so:libc.musl-x86_64.so.1]
               libcrypto1.0-1.0.2h-r1[so:libc.musl-x86_64.so.1]
               g++-5.3.0-r0[so:libc.musl-x86_64.so.1]
               postgresql-libs-9.6.0-r1[so:libc.musl-x86_64.so.1]
               mpfr3-3.1.2-r0[so:libc.musl-x86_64.so.1]
               ncurses-libs-6.0-r7[so:libc.musl-x86_64.so.1]
               libstdc++-5.3.0-r0[so:libc.musl-x86_64.so.1]
               libldap-2.4.44-r1[so:libc.musl-x86_64.so.1]
               libpq-9.6.0-r1[so:libc.musl-x86_64.so.1]
               postgresql-dev-9.6.0-r1[so:libc.musl-x86_64.so.1]
               xz-5.2.2-r1[so:libc.musl-x86_64.so.1]
               isl-0.14.1-r0[so:libc.musl-x86_64.so.1]
               libcurl-7.50.1-r0[so:libc.musl-x86_64.so.1]
               db-5.3.28-r0[so:libc.musl-x86_64.so.1]
               mpc1-1.0.3-r0[so:libc.musl-x86_64.so.1]
               libressl2.4-libcrypto-2.4.3-r1[so:libc.musl-x86_64.so.1]
               libmagic-5.27-r0[so:libc.musl-x86_64.so.1]
               libressl2.4-libssl-2.4.3-r1[so:libc.musl-x86_64.so.1]
               zlib-1.2.8-r2[so:libc.musl-x86_64.so.1]
               libgomp-5.3.0-r0[so:libc.musl-x86_64.so.1]
               apk-tools-2.6.7-r0[so:libc.musl-x86_64.so.1]
               libressl2.4-libtls-2.4.3-r1[so:libc.musl-x86_64.so.1]
               libssh2-1.7.0-r0[so:libc.musl-x86_64.so.1]
               re2c-0.14.3-r0[so:libc.musl-x86_64.so.1]
               libedit-20150325.3.1-r3[so:libc.musl-x86_64.so.1]
               libgcc-5.3.0-r0[so:libc.musl-x86_64.so.1]
               make-4.1-r1[so:libc.musl-x86_64.so.1]
               curl-7.50.1-r0[so:libc.musl-x86_64.so.1]
               alpine-baselayout-3.0.3-r0[so:libc.musl-x86_64.so.1]
               libatomic-5.3.0-r0[so:libc.musl-x86_64.so.1]
               xz-libs-5.2.2-r1[so:libc.musl-x86_64.so.1]
               perl-5.22.2-r0[so:libc.musl-x86_64.so.1]
               ca-certificates-20160104-r4[so:libc.musl-x86_64.so.1]
               libxml2-2.9.4-r0[so:libc.musl-x86_64.so.1]
               m4-1.4.17-r1[so:libc.musl-x86_64.so.1]
               gmp-6.1.0-r0[so:libc.musl-x86_64.so.1]
               tar-1.29-r0[so:libc.musl-x86_64.so.1]
               libsasl-2.1.26-r7[so:libc.musl-x86_64.so.1]
               busybox-1.24.2-r9[so:libc.musl-x86_64.so.1]
               scanelf-1.1.6-r0[so:libc.musl-x86_64.so.1]
               file-5.27-r0[so:libc.musl-x86_64.so.1]
               binutils-2.26-r0[so:libc.musl-x86_64.so.1]
               libssl1.0-1.0.2h-r1[so:libc.musl-x86_64.so.1]
  .phpize-deps-0:
    masked in: cache
    satisfies: world[.phpize-deps]
The command '/bin/sh -c apk add --update --no-cache "postgresql-dev@edge>9.5" "libpq@edge>9.5"     && docker-php-ext-install mcrypt mbstring pgsql pdo pdo_pgsql' returned a non-zero code: 56
```

**Comment by mh3720** [comment] 2016-10-24 23:06
Could this be caused by conflicting packages/versions between the stable and Edge repositories?

**Comment by mh3720** [comment] 2016-10-24 23:12
I tried separating the `apk add` and `docker-php-ext-install` commands into separate `RUN` directives, and then I tried isolating the individual packages.  The error happens during the `docker-php-ext-install` command, and it happens on *any* of the listed packages, so I believe the error is not package-specific.

**Comment by bkuhl** [comment] 2016-10-24 23:12
We used edge at the time because postgres 9.5 wasn't yet stable.  At this time we could probably switch back to stable.

**Comment by bkuhl** [comment] 2016-10-24 23:15
The same problem exists in https://github.com/realpage/php/pull/17.  This isn't just your local builds.

**Comment by mh3720** [comment] 2016-10-24 23:36
Related?

https://github.com/gliderlabs/docker-alpine/issues/93

http://www.alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html

**Comment by bkuhl** [comment] 2016-10-24 23:44
Great find Matt.  Our team just started a sprint today so we aren't able to dig into this issue until we've completed the work we've committed to.  We'd welcome a PR to address this.

**Comment by mh3720** [comment] 2016-10-24 23:56
https://github.com/realpage/php/pull/19

**Closed** 2016-10-25 00:10 UTC
